---
- name: Check existing install
  register: lsd_version_check
  failed_when: False
  changed_when: False
  check_mode: False
  shell: /usr/bin/lsd --version 2>&1
  tags:
    - lsd

- name: Fact version change
  set_fact:
    lsd_version_changed: "{{ lsd_version_check.rc != 0 or (lsd_version_check.stdout_lines is defined and lsd_version not in lsd_version_check.stdout_lines[0]) | bool }}"
  tags:
    - lsd

- name: Download release binary
  when:
    - lsd_version_changed
  unarchive:
    src: "{{ lsd_download }}"
    dest: /usr/local/src
    remote_src: True
    owner: root
    group: root
  tags:
    - lsd

- name: Copy downloaded binary
  when:
    - lsd_version_changed
    - not ansible_check_mode
  copy:
    src: "/usr/local/src/lsd-v{{ lsd_version }}-{{ lsd_arch }}/lsd"
    dest: /usr/bin/lsd
    remote_src: True
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - lsd

- name: Remove install directory
  file:
    path: "/usr/local/src/lsd-v{{ lsd_version }}-{{ lsd_arch }}"
    state: absent
  tags:
    - lsd

...
